name: Destroy Resource
on:
    workflow_dispatch:

jobs:
    destroy-resource:
        runs-on: ubuntu-latest
        environment: Dev

        steps:
            # Configure AWS Credential
            - name: Configure AWS Credential
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: 'us-east-1'
              run: |
                mkdir -p ~/.aws
                echo "[default]" > ~/.aws/credentials
                echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
                echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
                echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials

            # Execute terraform
            - name: Terraform init
              run: terraform init

            - name: Terraform destroy
              run: terraform destroy
            
            # Delete S3 bucket that contains terraform.tfstate
            - name: Delete S3 bucket that contains terraform.tfstate
              run: aws s3api delete-bucket --bucket bucket-4-tfstate-12345
        